# Site settings
baseurl = "omaribannez.com"
languageCode = "es"
title = "Omar Ibañez"
theme = "hugo-theme-cactus-plus"
googleAnalytics = "your_google_analytics_id"
# Set the value to true if your site include CJK (Chinese, Japanese, and Korean languages) characters
hasCJKLanguage = false

[params]
	author = "Omar Ibañez"
	description = "Blog sobre software engineering y data science"
	bio = "Engineering Lead @ Eastridge, Co-Founder @ Python Tijuana, Co-Founder @ Data Science Tijuana"

	twitter = "omaribannez"
	facebook = "omaribannez"

	enableRSS = true
	enableToc = true

	enableDisqus = true
	disqusShortname = "omaribannez"


	enableSummary = true
	# Set the value to true if use description in post front matter replace content summary
	useDescriptionReplaceSummary = false


	enableGoogleAnalytics = true
	enableBaiduAnalytics = false
	# Set the value to your baidu analysis code if you want to use baidu analytics
	baiduAnalytics = 'your_baidu_analysis_code'

	enableTwitterCard = true
	# The url for twitter card image, default is avatar.png in static/images directory
	twitterCardImage = ""

	# Add custom assets with their paths relative to the static folder
	customCSS = []
	customJS  = []

	# The variables below are optionally too and can be used to
	# translate or customize each string of the theme.

	# Navigation links
	home = ""
	about = "/about"
	archive = ""
	subscribe = ""

	olderPosts = ""
	newerPosts = ""
	copyright = ""

	# show latest posts in single page
	showLatestPosts = false
	readMore = ""

	# Share
	enableShare = true
	tweet = ""
	share = ""

	# 404 page
	title404 = "Insuficient data"
	subtitle404 = ""

	# Choose a font for the social icons in the footer. Either "mono-social" or "font-awesome"
	iconFont = "font-awesome"


# Add additional social link entries underneath
[social]
	facebook-square = "https://www.facebook.com/omaribannez"
	twitter-square = "https://www.twitter.com/omaribannez"
	github-square = "https://www.github.com/omaribannez"

